services:
    oneup.contao.language_dependent_modules_bundle.module.language_dependent_modules_surrogate:
        class: Oneup\Contao\LanguageDependentModulesBundle\Controller\FrontendModule\LanguageDependentModulesSurrogate
        public: true
        tags:
            - { name: contao.frontend_module, category: miscellaneous }

    oneup.contao.language_dependent_modules_bundle.provider.available_language_provider:
        class: Oneup\Contao\LanguageDependentModulesBundle\Provider\AvailableLanguageProvider
        public: true
        arguments:
            - '@database_connection'
            - '@translator'

    oneup.contao.language_dependent_modules_bundle.provider.module_provider:
        class: Oneup\Contao\LanguageDependentModulesBundle\Provider\ModuleProvider
        public: true
        arguments:
            - '@database_connection'

    oneup.contao.language_dependent_modules_bundle.listener.language_dependent_modules_surrogate_listener:
        class: Oneup\Contao\LanguageDependentModulesBundle\EventListener\LanguageDependentModulesSurrogateListener
        public: true
        arguments:
            - '@oneup.contao.language_dependent_modules_bundle.provider.available_language_provider'

    onup.contao.language_dependent_modules_bundle.listener.load_data_container_listener:
        class: Oneup\Contao\LanguageDependentModulesBundle\EventListener\LoadDataContainerListener
        public: true
        arguments:
            - '@oneup.contao.language_dependent_modules_bundle.provider.available_language_provider'
            - '@oneup.contao.language_dependent_modules_bundle.provider.module_provider'
            - '@translator'
            - '@contao.routing.scope_matcher'
            - '@request_stack'
        tags:
            - { name: contao.hook, hook: loadDataContainer }

    oneup.contao.language_dependent_modules_bundle.listener.field_wizard_listener:
        class: Oneup\Contao\LanguageDependentModulesBundle\EventListener\FieldWizardListener
        public: true
        arguments:
            - '@translator'
            - '@contao.csrf.token_manager'
            - '%contao.csrf_token_name%'
